language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t ankurvr/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true ankurvr/docker-react npm run test